### ISSUE TITLE
Archive Tweets and Reddit Posts

### ISSUE THREAD

**Issue by zuqini** [JustYourPythonEnvironment/CheeseKimBot#15]

**Comment by iFallUpHill** [comment]
Essentially duplicating this:
https://github.com/JustYourPythonEnvironment/CheeseKimBot/blob/master/utils/UrlValidator.js#L2

**Comment by iFallUpHill** [comment]
https://github.com/JustYourPythonEnvironment/CheeseKimBot/pull/17
